// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_database.proto

package br.com.sd.victor;

/**
 * Protobuf type {@code grpcdatabase.Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpcdatabase.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            key_ = input.readUInt64();
            break;
          }
          case 18: {
            br.com.sd.victor.Value.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(br.com.sd.victor.Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            checkingVersion_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.sd.victor.GrpcDatabaseProto.internal_static_grpcdatabase_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.sd.victor.GrpcDatabaseProto.internal_static_grpcdatabase_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.sd.victor.Request.class, br.com.sd.victor.Request.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private long key_;
  /**
   * <code>uint64 key = 1;</code>
   * @return The key.
   */
  public long getKey() {
    return key_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private br.com.sd.victor.Value value_;
  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   * @return Whether the value field is set.
   */
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   * @return The value.
   */
  public br.com.sd.victor.Value getValue() {
    return value_ == null ? br.com.sd.victor.Value.getDefaultInstance() : value_;
  }
  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   */
  public br.com.sd.victor.ValueOrBuilder getValueOrBuilder() {
    return getValue();
  }

  public static final int CHECKINGVERSION_FIELD_NUMBER = 3;
  private long checkingVersion_;
  /**
   * <code>uint64 checkingVersion = 3;</code>
   * @return The checkingVersion.
   */
  public long getCheckingVersion() {
    return checkingVersion_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (key_ != 0L) {
      output.writeUInt64(1, key_);
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    if (checkingVersion_ != 0L) {
      output.writeUInt64(3, checkingVersion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (key_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, key_);
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    if (checkingVersion_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, checkingVersion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.sd.victor.Request)) {
      return super.equals(obj);
    }
    br.com.sd.victor.Request other = (br.com.sd.victor.Request) obj;

    if (getKey()
        != other.getKey()) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (getCheckingVersion()
        != other.getCheckingVersion()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKey());
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (37 * hash) + CHECKINGVERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCheckingVersion());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.sd.victor.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.sd.victor.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.sd.victor.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.sd.victor.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.sd.victor.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.sd.victor.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.sd.victor.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.sd.victor.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.sd.victor.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.sd.victor.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.sd.victor.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.sd.victor.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.sd.victor.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpcdatabase.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpcdatabase.Request)
      br.com.sd.victor.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.sd.victor.GrpcDatabaseProto.internal_static_grpcdatabase_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.sd.victor.GrpcDatabaseProto.internal_static_grpcdatabase_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.sd.victor.Request.class, br.com.sd.victor.Request.Builder.class);
    }

    // Construct using br.com.sd.victor.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      key_ = 0L;

      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      checkingVersion_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.sd.victor.GrpcDatabaseProto.internal_static_grpcdatabase_Request_descriptor;
    }

    @java.lang.Override
    public br.com.sd.victor.Request getDefaultInstanceForType() {
      return br.com.sd.victor.Request.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.sd.victor.Request build() {
      br.com.sd.victor.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.sd.victor.Request buildPartial() {
      br.com.sd.victor.Request result = new br.com.sd.victor.Request(this);
      result.key_ = key_;
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      result.checkingVersion_ = checkingVersion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.sd.victor.Request) {
        return mergeFrom((br.com.sd.victor.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.sd.victor.Request other) {
      if (other == br.com.sd.victor.Request.getDefaultInstance()) return this;
      if (other.getKey() != 0L) {
        setKey(other.getKey());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (other.getCheckingVersion() != 0L) {
        setCheckingVersion(other.getCheckingVersion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.sd.victor.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.sd.victor.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long key_ ;
    /**
     * <code>uint64 key = 1;</code>
     * @return The key.
     */
    public long getKey() {
      return key_;
    }
    /**
     * <code>uint64 key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(long value) {
      
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = 0L;
      onChanged();
      return this;
    }

    private br.com.sd.victor.Value value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.sd.victor.Value, br.com.sd.victor.Value.Builder, br.com.sd.victor.ValueOrBuilder> valueBuilder_;
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     * @return The value.
     */
    public br.com.sd.victor.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? br.com.sd.victor.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public Builder setValue(br.com.sd.victor.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public Builder setValue(
        br.com.sd.victor.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public Builder mergeValue(br.com.sd.victor.Value value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            br.com.sd.victor.Value.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public br.com.sd.victor.Value.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    public br.com.sd.victor.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            br.com.sd.victor.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.grpcdatabase.Value value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.sd.victor.Value, br.com.sd.victor.Value.Builder, br.com.sd.victor.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.sd.victor.Value, br.com.sd.victor.Value.Builder, br.com.sd.victor.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private long checkingVersion_ ;
    /**
     * <code>uint64 checkingVersion = 3;</code>
     * @return The checkingVersion.
     */
    public long getCheckingVersion() {
      return checkingVersion_;
    }
    /**
     * <code>uint64 checkingVersion = 3;</code>
     * @param value The checkingVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCheckingVersion(long value) {
      
      checkingVersion_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 checkingVersion = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckingVersion() {
      
      checkingVersion_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpcdatabase.Request)
  }

  // @@protoc_insertion_point(class_scope:grpcdatabase.Request)
  private static final br.com.sd.victor.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.sd.victor.Request();
  }

  public static br.com.sd.victor.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.sd.victor.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

