// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_database.proto

package br.com.sd.victor;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdatabase.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 key = 1;</code>
   * @return The key.
   */
  long getKey();

  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   * @return The value.
   */
  br.com.sd.victor.Value getValue();
  /**
   * <code>.grpcdatabase.Value value = 2;</code>
   */
  br.com.sd.victor.ValueOrBuilder getValueOrBuilder();

  /**
   * <code>uint64 checkingVersion = 3;</code>
   * @return The checkingVersion.
   */
  long getCheckingVersion();
}
