// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_database.proto

package br.com.sd.victor;

public interface ValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcdatabase.Value)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 version = 1;</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>uint64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
